# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bfff30c76e8e4f3875a0a3b25fbd2fa134a554bcc42fdd674c05a62d0f2a777f77d1594eae64cbca3e71b8f7fd93153374e89105bbb27480e5f97a84c595ae2

test:
  secret_key_base: 443c25507d274a0bc63e769ea5902fab46e9e656fb7ac5dbb8d71dfa3eb9696bfb8eb7d50f836c2f8bc2e428f946e4fc114f7714247e057756d2d6f2ba62f461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
